### ISSUE TITLE
MacOS support 

### ISSUE THREAD

**Issue by LOG-TAG** [ArtCC/CreateViperModule_iOS#1]
can we use it for macOS app architecture also like https://github.com/strongself/Generamba ?

**Comment by ArtCC** [comment]
Hi!
Not for the view layer, I can upload a modification to work on macOS.
Regards,

Arturo.

**Comment by ArtCC** [comment]
Hi LOG-TAG,

Repo for macOS:

https://github.com/ArtCC/CreateViperModule_macOS

Thanks!
